blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/nitrocode/omaha-deals-map/discussions
    about: For general questions, use Discussions instead of an issue.
