#!/usr/bin/env python3
"""Render a shields.io endpoint-format JSON from a coverage.xml file.

Run after pytest --cov-report=xml. CI consumes the JSON via shields.io:
  https://img.shields.io/endpoint?url=<raw_url_to_this_file>

Why an endpoint JSON (not a static SVG)?
  - 100 bytes vs ~1 KB
  - No binary churn in git history
  - shields.io picks fonts / theming consistently with the rest of the
    badges in the README; we only supply the value + color band

Run:
    python scripts/coverage_badge.py [coverage.xml] [badge.json]
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

# stdlib XML is vulnerable to XXE / billion-laughs when parsing untrusted
# input. coverage.xml is generated by pytest-cov in the same CI step, so
# it's strictly first-party output, not an attacker injection vector.
# Adding `defusedxml` as a runtime dep would cost a lockfile entry and
# more supply-chain surface for zero real protection here. If this ever
# starts reading user-uploaded XML, switch to defusedxml.
from xml.etree import ElementTree as ET  # noqa: I001 (intentional placement after comment)

DEFAULT_INPUT = Path("coverage.xml")
DEFAULT_OUTPUT = Path(".github/badges/coverage.json")


def _color_for(pct: int) -> str:
    """Match the standard shields.io coverage color bands so the badge
    matches what other Python projects display."""
    if pct >= 90:
        return "brightgreen"
    if pct >= 80:
        return "green"
    if pct >= 70:
        return "yellowgreen"
    if pct >= 60:
        return "yellow"
    if pct >= 50:
        return "orange"
    return "red"


def render(input_path: Path, output_path: Path) -> int:
    if not input_path.is_file():
        print(f"[coverage-badge] {input_path} not found; "
              f"run pytest --cov-report=xml first", file=sys.stderr)
        return 1
    root = ET.parse(input_path).getroot()
    rate = float(root.get("line-rate", 0))
    pct = int(round(rate * 100))
    payload = {
        "schemaVersion": 1,
        "label": "coverage",
        "message": f"{pct}%",
        "color": _color_for(pct),
    }
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"[coverage-badge] {output_path} -> {pct}% ({payload['color']})")
    return 0


def main(argv: list[str]) -> int:
    inp = Path(argv[1]) if len(argv) > 1 else DEFAULT_INPUT
    out = Path(argv[2]) if len(argv) > 2 else DEFAULT_OUTPUT
    return render(inp, out)


if __name__ == "__main__":
    sys.exit(main(sys.argv))
